# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SailpointCli < Formula
  desc ""
  homepage "https://github.com/sailpoint-oss/sailpoint-cli"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sailpoint-oss/sailpoint-cli/releases/download/1.0.0/sail_1.0.0_darwin_arm64.tar.gz"
      sha256 "d72b7def60b635a7e881cb1e46924732c3042f9f7b36069e678e8f41a28b948a"

      def install
        bin.install "sail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sailpoint-oss/sailpoint-cli/releases/download/1.0.0/sail_1.0.0_darwin_amd64.tar.gz"
      sha256 "4e2eb190c3487424001b3a84de985ba2e018ca74e8a6b12ade23cb28f599d9e9"

      def install
        bin.install "sail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sailpoint-oss/sailpoint-cli/releases/download/1.0.0/sail_1.0.0_linux_amd64.tar.gz"
      sha256 "adf8c7b63f1f6819bfe32f851d8fc48f6105dee7a03b2b94c31f6e60b603b31c"

      def install
        bin.install "sail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sailpoint-oss/sailpoint-cli/releases/download/1.0.0/sail_1.0.0_linux_arm64.tar.gz"
      sha256 "96d8222e4def2f1084e0932e093fc3a6307f08e5eed1c5e2b19cfd3ea201ddfc"

      def install
        bin.install "sail"
      end
    end
  end
end
