# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SailpointCli < Formula
  desc ""
  homepage "https://github.com/sailpoint-oss/sailpoint-cli"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sailpoint-oss/sailpoint-cli/releases/download/0.5.0/sail_0.5.0_darwin_arm64.tar.gz"
      sha256 "eb8034586db48f61f2a65ac3bd35e768f4a41443647027c2133baf8125d42259"

      def install
        bin.install "sail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sailpoint-oss/sailpoint-cli/releases/download/0.5.0/sail_0.5.0_darwin_amd64.tar.gz"
      sha256 "5254482a7dccb736a4ad5cdd078288937718544a764aea92ea600eb8412c309d"

      def install
        bin.install "sail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sailpoint-oss/sailpoint-cli/releases/download/0.5.0/sail_0.5.0_linux_arm64.tar.gz"
      sha256 "516bebf64b5d48391ef0fbe3c5357f6ef1d3dc7698d33010484fc045e10157e7"

      def install
        bin.install "sail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sailpoint-oss/sailpoint-cli/releases/download/0.5.0/sail_0.5.0_linux_amd64.tar.gz"
      sha256 "13d7c151186b3c84c63af18f09af52121b717597a27e6360a2d406e1f109841e"

      def install
        bin.install "sail"
      end
    end
  end
end
